spring.application.name=backend
server.port=8080

spring.data.mongodb.uri=mongodb+srv://adrsandeepani_db_user:4o4pTyEH68Xe87n5@hospitalcluster.a8agoxd.mongodb.net/?retryWrites=true&w=majority&appName=HospitalCluster

spring.data.mongodb.database=hpms_db