spring.application.name=backend
server.port=8080

spring.data.mongodb.uri=${MONGODB_URI}
spring.data.mongodb.database=hpms_db
spring.web.resources.cache.cachecontrol.no-store=true
spring.web.resources.cache.cachecontrol.no-cache=true
spring.web.resources.cache.cachecontrol.must-revalidate=true